export const CANON_QUOTES = [
  "Você foi autorizado.",
  "Entre o primeiro bit e o último suspiro.",
  "Leitura não recomendada para mentes programadas para obediência cega.",
  "Alguns nomes foram preservados.",
  "Alguns eventos permanecem sem origem confirmada.",
  "Não há garantia de que todas as conexões estejam explícitas.",
  "Nem de que todas as lacunas sejam acidentais.",
  "Nada aqui foi incluído sem motivo.",
  "Nem tudo aqui pôde ser incluído.",
  "Se você está lendo este material, é porque o acesso foi permitido.",
  "A pergunta que permanece não é quando isso começou.",
  "Mas em que momento deixou de ser possível interromper.",
  "Era como abrir uma porta sem saber para onde levava.",
  "Mas entrar mesmo assim.",
  "Mas ninguém ouvia. Porque ainda era cedo.",
  "Isso apareceu sozinho.",
  "Às vezes, a máquina continua de onde a gente parou.",
  "Sem nobreak, sem estabilizador.",
  "Tela preta. Tudo se foi em um segundo.",
  "O medo é uma forma de reconhecimento.",
] as const;
